export const configShipTypes = async () => {
	return {
		flagship: {
			name: "The Flagship",
			attributes: {
				description: [
					{ name: "Imposing", selected: false},
					{ name: "Angular", selected: false},
					{ name: "Tough", selected: false},
					{ name: "Graceful", selected: false},
					{ name: "Revolutionary", selected: false},
					{ name: "Disturbing", selected: false},
					{ name: "Streamlined", selected: false},
					{ name: "Inspiring", selected: false},
				],
				crewSize: [
					game.i18n.localize("Starscape.Ship.Attributes.Crew.small"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.medium"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.large"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.massive"),	
				],
				propulsion: [
					{name: "Faster Than Light Travel", selected: false},
					{name: "Jump Points", selected: false},
					{name: "Combustion Engine", selected: false},
				],
				defenses: [
					{name: "Energy Force Field", selected: false},
					{name: "Flares or Decoys", selected: false},
					{name: "No Defenses", selected: false},
				],
				weapons: [
					{name: "Laser Weapons", selected: false},
					{name: "Projectiles", selected: false},
					{name: "No Weapons", selected: false},
				],
				quirks: [
					{name: "It is always identifiable, respected by most", selected: true, required: true},
					{name: "It never runs out of power, but the source is dangerous", selected: false, required: false},
					{name: "It's basically brand new but parts aren't publicly available", selected: false, required: false},
					{name: "Has the backing of a powerful organization and its political entanglements", selected: false, required: false},
				],
				areas: [
					{ name: "Airlocks", selected: false, requiresCount: true, custom: false},
					{ name: "Armory", selected: false, requiresCount: false, custom: false},
					{ name: "Bridge", selected: false, requiresCount: false, custom: false},
					{ name: "Cockpit", selected: false, requiresCount: false, custom: false},
					{ name: "Brig", selected: false, requiresCount: false, custom: false},
					{ name: "Security", selected: false, requiresCount: false, custom: false},
					{ name: "Cargo Hold", selected: false, requiresCount: false, custom: false},
					{ name: "Hangar Bay", selected: false, requiresCount: false, custom: false},
					{ name: "Bunks", selected: false, requiresCount: false, custom: false},
					{ name: "Crew Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Officer Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Passenger Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Conference Room", selected: false, requiresCount: false, custom: false},
					{ name: "Ready Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engine Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engineering", selected: false, requiresCount: false, custom: false},
					{ name: "Galley", selected: false, requiresCount: false, custom: false},
					{ name: "Mess Hall", selected: false, requiresCount: false, custom: false},
					{ name: "Infirmary", selected: false, requiresCount: false, custom: false},
					{ name: "", selected: false, requiresCount: false, custom: true},
					{ name: "", selected: false, requiresCount: false, custom: true},
				]
			}
		},
		behemoth: {
			name: "The Behemoth",
			attributes: {
				description: [
					{ name: "Outdated", selected: false},
					{ name: "Warlike", selected: false},
					{ name: "Damaged", selected: false},
					{ name: "Changed", selected: false},
					{ name: "Dull", selected: false},
					{ name: "Confusing", selected: false},
					{ name: "Gratuitous", selected: false},
					{ name: "Practical", selected: false},
				],
				crewSize: [
					game.i18n.localize("Starscape.Ship.Attributes.Crew.small"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.medium"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.large"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.massive"),	
				],
				propulsion: [
					{name: "Faster Than Light Travel", selected: false},
					{name: "Jump Points", selected: false},
					{name: "Combustion Engine", selected: false},
				],
				defenses: [
					{name: "Energy Force Field", selected: false},
					{name: "Flares or Decoys", selected: false},
					{name: "No Defenses", selected: false},
				],
				weapons: [
					{name: "Laser Weapons", selected: false},
					{name: "Projectiles", selected: false},
					{name: "Ramming or Collision Elements", selected: false},
					{name: "No Weapons", selected: false},
				],
				quirks: [
					{name: "Draws a lot of attention and does not blend in", selected: true, required: true},
					{name: "Has massive amounts of resources but also unexpected cargo that you can't get rid of", selected: false, required: false},
					{name: "It never needs to be refueled but uses technology that you don't understand", selected: false, required: false},
					{name: "Has a powerful reputation but also an infamous past", selected: false, required: false},
				],
				areas: [
					{ name: "Airlocks", selected: false, requiresCount: true, custom: false},
					{ name: "Armory", selected: false, requiresCount: false, custom: false},
					{ name: "Bridge", selected: false, requiresCount: false, custom: false},
					{ name: "Brig", selected: false, requiresCount: false, custom: false},
					{ name: "Security", selected: false, requiresCount: false, custom: false},
					{ name: "Cargo", selected: false, requiresCount: true, custom: false},
					{ name: "Hangar Bay", selected: false, requiresCount: false, custom: false},
					{ name: "Bunks", selected: false, requiresCount: false, custom: false},
					{ name: "Crew Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Officer Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Passenger Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Conference Room", selected: false, requiresCount: false, custom: false},
					{ name: "Ready Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engine Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engineering", selected: false, requiresCount: false, custom: false},
					{ name: "Galley", selected: false, requiresCount: false, custom: false},
					{ name: "Mess Hall", selected: false, requiresCount: false, custom: false},
					{ name: "Infirmary", selected: false, requiresCount: false, custom: false},
					{ name: "", selected: false, requiresCount: false, custom: true},
					{ name: "", selected: false, requiresCount: false, custom: true},
				]
			}
		},
		lightFreighter: {
			name: "The Light Freighter",
			attributes: {
				description: [
					{ name: "Customized", selected: false},
					{ name: "Well-Kept", selected: false},
					{ name: "Elegant", selected: false},
					{ name: "Worn", selected: false},
					{ name: "Deceptive", selected: false},
					{ name: "Welcoming", selected: false},
					{ name: "Mismatched", selected: false},
					{ name: "Clunky", selected: false},
				],
				crewSize: [
					game.i18n.localize("Starscape.Ship.Attributes.Crew.small"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.massive"),	
				],
				propulsion: [
					{name: "Combustion Engine", selected: false},
					{name: "Jump Points", selected: false},
					{name: "Rides on Solar Winds", selected: false},
				],
				defenses: [
					{name: "Armored Hull", selected: false},
					{name: "Flares or Decoys", selected: false},
					{name: "No Defenses", selected: false},
				],
				weapons: [
					{name: "Laser Weapons", selected: false},
					{name: "Projectiles", selected: false},
					{name: "No Weapons", selected: false},
				],
				quirks: [
					{name: "It is nondescript and unimpressive to outside observers", selected: true, required: true},
					{name: "You can change identification data, but someone bad knows you on sight", selected: false, required: false},
					{name: "You have a high-tech upgrade but are still paying for it", selected: false, required: false},
					{name: "A part of your ship is of unknown origin", selected: false, required: false},
				],
				areas: [
					{ name: "Airlocks", selected: false, requiresCount: true, custom: false},
					{ name: "Armory", selected: false, requiresCount: false, custom: false},
					{ name: "Bridge", selected: false, requiresCount: false, custom: false},
					{ name: "Cockpit", selected: false, requiresCount: false, custom: false},
					{ name: "Brig", selected: false, requiresCount: false, custom: false},
					{ name: "Security", selected: false, requiresCount: false, custom: false},
					{ name: "Cargo Hold", selected: false, requiresCount: false, custom: false},
					{ name: "Hangar Bay", selected: false, requiresCount: false, custom: false},
					{ name: "Bunks", selected: false, requiresCount: false, custom: false},
					{ name: "Crew Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Officer Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Passenger Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Conference Room", selected: false, requiresCount: false, custom: false},
					{ name: "Ready Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engine Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engineering", selected: false, requiresCount: false, custom: false},
					{ name: "Galley", selected: false, requiresCount: false, custom: false},
					{ name: "Mess Hall", selected: false, requiresCount: false, custom: false},
					{ name: "Infirmary", selected: false, requiresCount: false, custom: false},
					{ name: "", selected: false, requiresCount: false, custom: true},
					{ name: "", selected: false, requiresCount: false, custom: true},
				]
			}
		},
		throwback: {
			name: "The Throwback",
			attributes: {
				description: [
					{ name: "Proud", selected: false},
					{ name: "Antique", selected: false},
					{ name: "Refurbished", selected: false},
					{ name: "Replica", selected: false},
					{ name: "Reliable", selected: false},
					{ name: "Listing", selected: false},
					{ name: "Untested", selected: false},
					{ name: "Common", selected: false},
				],
				crewSize: [
					game.i18n.localize("Starscape.Ship.Attributes.Crew.small"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.medium"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.large"),
				],
				propulsion: [
					{name: "Steam Powered", selected: false},
					{name: "Sails on Solar Winds", selected: false},
					{name: "Rides on Galactic Ley Lines", selected: false},
				],
				defenses: [
					{name: "Armored Hull", selected: false},
					{name: "Deck Traps", selected: false},
					{name: "No Defenses", selected: false},
				],
				weapons: [
					{name: "Ramming or Collision Elements", selected: false},
					{name: "Projectiles", selected: false},
					{name: "No Weapons", selected: false},
				],
				quirks: [
					{name: "Needs no fuel, but is dependent on the winds or moisture recycler", selected: true, required: true},
					{name: "Brand new but obtained through piracy or nefarious means", selected: false, required: false},
					{name: "Has a celebrated past, but is now barely holding together", selected: false, required: false},
					{name: "Survived a former crew;s death, but now unsettling things happen on board", selected: false, required: false},
				],
				areas: [
					{ name: "Airlocks", selected: false, requiresCount: true, custom: false},
					{ name: "Armory", selected: false, requiresCount: false, custom: false},
					{ name: "Bridge", selected: false, requiresCount: false, custom: false},
					{ name: "Cockpit", selected: false, requiresCount: false, custom: false},
					{ name: "Brig", selected: false, requiresCount: false, custom: false},
					{ name: "Security", selected: false, requiresCount: false, custom: false},
					{ name: "Cargo Hold", selected: false, requiresCount: false, custom: false},
					{ name: "Hangar Bay", selected: false, requiresCount: false, custom: false},
					{ name: "Bunks", selected: false, requiresCount: false, custom: false},
					{ name: "Crew Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Officer Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Passenger Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Conference Room", selected: false, requiresCount: false, custom: false},
					{ name: "Ready Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engine Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engineering", selected: false, requiresCount: false, custom: false},
					{ name: "Galley", selected: false, requiresCount: false, custom: false},
					{ name: "Mess Hall", selected: false, requiresCount: false, custom: false},
					{ name: "Infirmary", selected: false, requiresCount: false, custom: false},
					{ name: "", selected: false, requiresCount: false, custom: true},
					{ name: "", selected: false, requiresCount: false, custom: true},
				]
			}
		},
		livingBeing: {
			name: "The Living Being",
			attributes: {
				description: [
					{ name: "Scaled", selected: false},
					{ name: "Smooth", selected: false},
					{ name: "Mysterious", selected: false},
					{ name: "Wise", selected: false},
					{ name: "Moody", selected: false},
					{ name: "Disfigured", selected: false},
					{ name: "Curious", selected: false},
					{ name: "Calculating", selected: false},
				],
				crewSize: [
					game.i18n.localize("Starscape.Ship.Attributes.Crew.small"),
					game.i18n.localize("Starscape.Ship.Attributes.Crew.medium"),
				],
				propulsion: [
					{name: "Self-Propelled by Limbs", selected: false},
					{name: "Sails on Solar Winds", selected: false},
					{name: "Rides on Galactic Ley Lines", selected: false},
				],
				defenses: [
					{name: "Natural Armor", selected: false},
					{name: "Constructed Armor", selected: false},
					{name: "Ink or Gas Cloud", selected: false},
					{name: "Uncontrolled Flight", selected: false},
					{name: "No Defenses", selected: false},
				],
				weapons: [
					{name: "Ramming Capabilities", selected: false},
					{name: "Projectiles", selected: false},
					{name: "Energy Blasts", selected: false},
					{name: "No Weapons", selected: false},
				],
				quirks: [
					{name: "Can assist the crew but has a mind of its own", selected: true, required: true},
					{name: "Can communicate directly but has a lot of opinions", selected: false, required: false},
					{name: "Is an experienced traveler but is getting old", selected: false, required: false},
					{name: "Is in the prime of life but at some point will need to reproduce", selected: false, required: false},
				],
				areas: [
					{ name: "Airlocks", selected: false, requiresCount: true, custom: false},
					{ name: "Armory", selected: false, requiresCount: false, custom: false},
					{ name: "Bridge", selected: false, requiresCount: false, custom: false},
					{ name: "Cockpit", selected: false, requiresCount: false, custom: false},
					{ name: "Brig", selected: false, requiresCount: false, custom: false},
					{ name: "Security", selected: false, requiresCount: false, custom: false},
					{ name: "Cargo Hold", selected: false, requiresCount: false, custom: false},
					{ name: "Hangar Bay", selected: false, requiresCount: false, custom: false},
					{ name: "Bunks", selected: false, requiresCount: false, custom: false},
					{ name: "Crew Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Officer Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Passenger Quarters", selected: false, requiresCount: false, custom: false},
					{ name: "Conference Room", selected: false, requiresCount: false, custom: false},
					{ name: "Ready Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engine Room", selected: false, requiresCount: false, custom: false},
					{ name: "Engineering", selected: false, requiresCount: false, custom: false},
					{ name: "Galley", selected: false, requiresCount: false, custom: false},
					{ name: "Mess Hall", selected: false, requiresCount: false, custom: false},
					{ name: "Infirmary", selected: false, requiresCount: false, custom: false},
					{ name: "", selected: false, requiresCount: false, custom: true},
					{ name: "", selected: false, requiresCount: false, custom: true},
				]
			}
		},
	};
}